AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  ShopeeApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: shopee-api-dev-summary
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          ENVIRONMENT: dev
