name: CI
on:
  push:
    branches: [ "main", "frontend"]
  pull_request:
    branches: [ "main", "frontend"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm test
      - run: npm run build
