name: Deploy to AWS Lambda
on:
  push:
    branches: [backend]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install zip tool
        uses: montudor/action-zip@v1

      - name: Create Zip file for Lambda function
        run: |
          mkdir lambda-package
          cp lambda_function.py lambda-package/
          cd lambda-package
          zip -r ../code.zip .

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Publish Lambda and capture version
        id: publish
        run: |
          VERSION=$(aws lambda update-function-code \
            --function-name shopee-api-dev-summary \
            --zip-file fileb://code.zip \
            --publish \
            --query Version \
            --output text)
          echo "Published version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-southeast-1"

      - name: Show published version
        run: echo "Published version: ${{ steps.publish.outputs.version }}"
