name: Deploy to AWS Lambda

on:
  push:
    branches: [backend]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Create deployment package
        run: |
          mkdir lambda-package
          cp lambda_function.py lambda-package/
          cp shopee_utils.py lambda-package/
          cd lambda-package
          zip -r ../code.zip .

      - name: Deploy Lambda and capture version
        id: deploy_lambda
        run: |
          VERSION=$(aws lambda update-function-code \
            --function-name shopee-api-dev-summary \
            --zip-file fileb://code.zip \
            --publish \
            --query Version \
            --output text)
          echo "Lambda published version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-southeast-1

      - name: Show published version
        run: echo "Published Lambda version is ${{ steps.deploy_lambda.outputs.version }}"
