name: CI
on:
  push:
    branches: [ "main", "frontend"]
  pull_request:
    branches: [ "main", "frontend"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v4
        with:
          node-version: 20
      - name: CI test
        run: echo Ci testing
      - run: npm ci
      - run: npm test
      - run: npm run build
